name: Run Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16'

    - name: Install Dependencies
      run: npm install
    - name: Set Environment Variables
      run: |
        sed -i "s|__API_URL__|${{ secrets.API_URL }}|g" src/environments/environment.prod.ts
        sed -i "s|__API_KEY__|${{ secrets.API_KEY }}|g" src/environments/environment.prod.ts

    - name: Run Tests
      run: npm test -- --watch=false --code-coverage
