name: Run Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16'

    - name: Install Dependencies
      run: npm install
    - name: Set Environment Variables
      run: |
        echo "API_URL=${{ secrets.API_URL }}" >> $GITHUB_ENV
        echo "API_KEY=${{ secrets.API_KEY }}" >> $GITHUB_ENV
    - name: Run Tests
      run: npm test -- --watch=false --code-coverage
